package com.example.musicapp;

import android.media.MediaPlayer;

public class Array {

    //Массив для JAZZ - начало
    final int[] imgs1 = {
            R.drawable.atrain_backgroundd,
            R.drawable.roundmidnight,
            R.drawable.fly_me_to_the_moon,
            R.drawable.mood_indugo,
            R.drawable.wonderful_world,
            R.drawable.strange_fruit,
            R.drawable.georgia_on_my_mind,
            R.drawable.summertime,
            R.drawable.my_funny_valentaine,
            R.drawable.cry_me_a_river,
            R.drawable.i_got_rhytm,
            R.drawable.night_and_day,
            R.drawable.at_last,
            R.drawable.mercy_mercy_mercy,
            R.drawable.blue_rondo_a_la_turk,
            R.drawable.aint_misbehavin,
            R.drawable.bye_bye_blackbird,
            R.drawable.april_in_paris,
            R.drawable.sidewinder,
            R.drawable.one_oclock_jump,
    };


    final int[] text1 = {
            R.string.jazz1,
            R.string.jazz2,
            R.string.jazz3,
            R.string.jazz4,
            R.string.jazz5,
            R.string.jazz6,
            R.string.jazz7,
            R.string.jazz8,
            R.string.jazz9,
            R.string.jazz10,
            R.string.jazz11,
            R.string.jazz12,
            R.string.jazz13,
            R.string.jazz14,
            R.string.jazz15,
            R.string.jazz16,
            R.string.jazz17,
            R.string.jazz18,
            R.string.jazz19,
            R.string.jazz20,
    };
    //Массив для JAZZ - конец

    //Массив с мелодиями - начало
    final int[] jazzsounds = {
            R.raw.takeatrain,
            R.raw.roundmidnigt,
            R.raw.flymetothemoon,
            R.raw.moodindigo,
            R.raw.whatawonderfulworld,
            R.raw.strangefruit,
            R.raw.georgiainmymind,
            R.raw.summertime,
            R.raw.myfunnyvalentaine,
            R.raw.crymeariver,
            R.raw.igotrhythm,
            R.raw.nightandday,
            R.raw.atlast,
            R.raw.mercymercymercy,
            R.raw.bluerondoalaturk,
            R.raw.aintmisbeheven,
            R.raw.byebyeblackbird,
            R.raw.aprilinparis,
            R.raw.sidewinder,
            R.raw.oneoclockjump,
    };
    //Массив с мелодиями - конец

    final int[] img_2 = {
            R.drawable.purplehaze,
            R.drawable.wholelottalove,
            R.drawable.babaoriley,
            R.drawable.sympathyforthedevil,
            R.drawable.smokeonthewater,
            R.drawable.bohemianrhapsody,
            R.drawable.roadhouseblues,
            R.drawable.hotelcalifornia,
            R.drawable.comfortablynumb,
            R.drawable.lagrange,
            R.drawable.sweetchildomine,
            R.drawable.rockyoulikeahurricane,
            R.drawable.tomsawyer,
            R.drawable.iloverocknroll,
            R.drawable.sultanofswings,
            R.drawable.underpressure,
            R.drawable.immigrantsong,
            R.drawable.justwhatineeded,
            R.drawable.theboysarebackintown,
            R.drawable.dreams,
    };

    final int[] text2 = {
            R.string.rock1,
            R.string.rock2,
            R.string.rock3,
            R.string.rock4,
            R.string.rock5,
            R.string.rock6,
            R.string.rock7,
            R.string.rock8,
            R.string.rock9,
            R.string.rock10,
            R.string.rock11,
            R.string.rock12,
            R.string.rock13,
            R.string.rock14,
            R.string.rock15,
            R.string.rock16,
            R.string.rock17,
            R.string.rock18,
            R.string.rock19,
            R.string.rock20,
    };

    final int[] rocksounds = {
            R.raw.purplehaze,
            R.raw.wholelottalove,
            R.raw.babaoriley,
            R.raw.sympathyforthedevil,
            R.raw.smokeonthewater,
            R.raw.bohemianrhapsody,
            R.raw.roadhouseblues,
            R.raw.hotelcalifornia,
            R.raw.comfortablynumb,
            R.raw.lagrange,
            R.raw.sweetchildomine,
            R.raw.rockyoulikeahurricane,
            R.raw.tomsawyer,
            R.raw.iloverocknroll,
            R.raw.sultanofswings,
            R.raw.underpressure,
            R.raw.immigrantsong,
            R.raw.justwhatineeded,
            R.raw.theboysarebackintown,
            R.raw.dreams,
    };

    final int[] img_3 = {
            R.drawable.justafriends,
            R.drawable.badandboujee,
            R.drawable.opp,
            R.drawable.bodakyellow,
            R.drawable.twoonetwo,
            R.drawable.kickpush,
            R.drawable.inthemorning,
            R.drawable.crushonyou,
            R.drawable.grindin,
            R.drawable.amilli,
            R.drawable.letmeblowyamind,
            R.drawable.californialove,
            R.drawable.getlow,
            R.drawable.savage,
            R.drawable.indaclub,
            R.drawable.insaneinthemembrane,
            R.drawable.backthatazzup,
            R.drawable.unity,
            R.drawable.itwasagoodday,
    };

    final int[] text3 = {
            R.string.hiphop1,
            R.string.hiphop2,
            R.string.hiphop3,
            R.string.hiphop4,
            R.string.hiphop5,
            R.string.hiphop6,
            R.string.hiphop7,
            R.string.hiphop8,
            R.string.hiphop9,
            R.string.hiphop10,
            R.string.hiphop11,
            R.string.hiphop12,
            R.string.hiphop13,
            R.string.hiphop14,
            R.string.hiphop15,
            R.string.hiphop16,
            R.string.hiphop17,
            R.string.hiphop18,
            R.string.hiphop19,
            R.string.hiphop20,
    };

    final int[] hiphopsounds = {
            R.raw.justafriends,
            R.raw.badandbouje,
            R.raw.opp,
            R.raw.bodakyellow,
            R.raw.blowthewhistle,
            R.raw.twoonetwo,
            R.raw.kickpush,
            R.raw.inthemorning,
            R.raw.crushonyou,
            R.raw.grindin,
            R.raw.amilli,
            R.raw.letmeblowyamind,
            R.raw.californialove,
            R.raw.getlow,
            R.raw.savage,
            R.raw.indaclub,
            R.raw.insaneinthemembrane,
            R.raw.backthatazzup,
            R.raw.unity,
            R.raw.itwasagoodday,
    };

    final int[] img_4 = {
            R.drawable.devil,
            R.drawable.howlong,
            R.drawable.coldheart,
            R.drawable.takemybreath,
            R.drawable.visitinghours,
            R.drawable.calmdown,
            R.drawable.finishline,
            R.drawable.fingerscrossed,
            R.drawable.blindinglights,
            R.drawable.overpassgraffiti,
            R.drawable.afterall,
            R.drawable.sacifice,
            R.drawable.oursong,
            R.drawable.notaboutus,
            R.drawable.wildestdreams,
            R.drawable.myuniverse,
            R.drawable.angelslullaby,
            R.drawable.ghost,
            R.drawable.cruelsummer,
            R.drawable.lightswitch,
    };

    final int[] text4 = {
            R.string.pop1,
            R.string.pop2,
            R.string.pop3,
            R.string.pop4,
            R.string.pop5,
            R.string.pop6,
            R.string.pop7,
            R.string.pop8,
            R.string.pop9,
            R.string.pop10,
            R.string.pop11,
            R.string.pop12,
            R.string.pop13,
            R.string.pop14,
            R.string.pop15,
            R.string.pop16,
            R.string.pop17,
            R.string.pop18,
            R.string.pop19,
            R.string.pop20,
    };

    final int[] popsounds = {
            R.raw.devil,
            R.raw.howlong,
            R.raw.coldheart,
            R.raw.takemybreath,
            R.raw.visitinghours,
            R.raw.calmdown,
            R.raw.finishline,
            R.raw.fingerscrossed,
            R.raw.blindinglights,
            R.raw.overpassgraffiti,
            R.raw.afterall,
            R.raw.sacifice,
            R.raw.oursong,
            R.raw.notaboutus,
            R.raw.wildestdreams,
            R.raw.myuniverse,
            R.raw.angelslullaby,
            R.raw.ghost,
            R.raw.cruelsummer,
            R.raw.lightswitch,
    };
}
